# Copyright 2019-2020, Cray Inc. All Rights Reserved.
---

- name: Create the keycloak-certs-local Kubernetes resource file
  template:
    src: keycloak-certs-local.yaml.j2
    dest: /root/k8s/keycloak-certs-local.yaml

- name: Apply the keycloak-certs-local Kubernetes resource file
  command: kubectl apply -f keycloak-certs-local.yaml
  args:
    chdir: /root/k8s

- name: Restart keycloak to pick up new CA cert
  command: kubectl rollout restart statefulset -n {{ keycloak_namespace }} cray-keycloak

- name: Wait for keycloak to be updated, step 1, updatedReplicas indicates update started
  command: kubectl get statefulset -n {{ keycloak_namespace }} cray-keycloak -ojsonpath='{.status.updatedReplicas}'
  register: result
  until: (result.stdout | int if result.stdout else 0) >= 1
  retries: 60
  delay: 5
  changed_when: false

- name: Wait for keycloak to be updated, step2, currentReplicas indicates keycloak running with update
  command: kubectl get statefulset -n {{ keycloak_namespace }} cray-keycloak -ojsonpath='{.status.currentReplicas}'
  register: result
  until: (result.stdout | int if result.stdout else 0) >= 1
  retries: 60
  delay: 5
  changed_when: false

- name: Wait for keycloak to be updated, step3, readyReplicas keycloak is available
  command: kubectl get statefulset -n {{ keycloak_namespace }} cray-keycloak -ojsonpath='{.status.readyReplicas}'
  register: result
  until: (result.stdout | int if result.stdout else 0) >= 1
  retries: 60
  delay: 5
  changed_when: false
