---
schema: v2
name: keycloak-gatekeeper
version: 1.0.0
failOnFirstError: True
repositories:
  docker: registry.local
  helm: charts.local
charts: # Will install/upgrade charts in the order below, latest versions of charts are auto-detected at manifestgen time if explicit version is not provided here
- name: "cray-keycloak-gatekeeper"
  namespace: "services"
  overrides:
  - image.repository="{repos[docker]}/keycloak/keycloak-gatekeeper"
