# Copyright 2019, Cray Inc. All Rights Reserved.
---
# Version of the Keycloak image
keycloak_image_version: 9.0.0

# Keycloak service name. This must be a valid service name.
keycloak_service_name: keycloak

# Version of the postgres image for keycloak-database
keycloak_postgres_image_version: 9.5

# Version of the keycloak alpine image
keycloak_alpine_image_version: 3.7

storage_method_keycloak: "{{ storage_default_method }}"
storage_class_keycloak: "{{ storage_default_class }}"
storage_size_keycloak: "{{ storage_default_size }}"

# This is where the data for Keycloak's database is stored.
# This is not used when storage_method_keycloak == storage_method_type_pvc
keycloak_db_volume: /var/keycloak-postgres/data

keycloak_master_admin_user: admin
keycloak_master_admin_password: adminpwd

# The namespace that keycloak objects are in.
keycloak_namespace: services

keycloak_setup_version: latest
keycloak_setup_repository: "{{ cray_stack_registry_source }}/cray/cray-keycloak-setup"
keycloak_setup_image: "{{ keycloak_setup_repository }}:{{ keycloak_setup_version }}"
keycloak_setup_image_pull_policy: Always

keycloak_master_admin_secret_name: keycloak-master-admin-auth

keycloak_api_gateway_service_dnsname: api-gw-service-nmn.local
keycloak_route: /keycloak

keycloak_admin_client_id: admin-client
keycloak_admin_client_secret_name: admin-client-auth
keycloak_admin_client_secret_namespaces:
  - "{{ keycloak_namespace }}"
  - default
  - ims

# DEPRECATION WARNING: keycloak_admin_client_auth_secret_name is deprecated in
# favor of keycloak_admin_client_secret_name (see above). As such, expect it to
# be removed in a future release.
keycloak_admin_client_auth_secret_name: "{{ keycloak_admin_client_secret_name }}"

keycloak_gatekeeper_client_id: gatekeeper
keycloak_gatekeeper_client_secret_name: keycloak-gatekeeper-client
keycloak_gatekeeper_client_secret_namespaces:
  - "{{ keycloak_namespace }}"

keycloak_customer_access_url: "https://auth.{{ shasta_domain }}{{ keycloak_route }}"

keycloak_gatekeeper_proxied_hosts:
  - "{{ shs_prometheus }}"
  - "{{ shs_alertmanager }}"
  - "{{ shs_grafana }}"
  - "{{ istio_prometheus }}"
  - "{{ istio_grafana }}"
  - "{{ istio_kiali }}"
  - "{{ istio_jaeger }}"
  - "{{ kube_monitoring_prometheus }}"
  - "{{ kube_monitoring_alertmanager }}"
  - "{{ kube_monitoring_grafana }}"
  - "{{ ceph_monitoring_prometheus }}"
  - "{{ vcs_hostname }}"
  - "sma-grafana.{{ shasta_domain }}"
  - "sma-kibana.{{ shasta_domain }}"

keycloak_gatekeeper_host_aliases: {}

# This is present for backwards compatibility.
# Use keycloak_admin_client_secret_name because this is going away.
# TODO: Remove this (see CASMCMS-3381)
kong_admin_client_auth_secret_name: "{{ keycloak_admin_client_secret_name }}"
