{{- /*
Copyright 2020 Hewlett Packard Enterprise Development LP
*/ -}}

# This was originally copied from the cray-service chart

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "keycloak"
  labels:
    app.kubernetes.io/name: keycloak
spec:
  hosts:
    - "*"
  gateways:
    - services-gateway
  http:
    # This route rule sets the Cache-Control response header when fetching
    # certs so that clients (e.g., OPA) will cache it.
    - match:
        - uri:
            exact: "/keycloak/realms/shasta/protocol/openid-connect/certs"
          method:
            exact: "GET"
      rewrite:
        uri: "/keycloak/realms/shasta/protocol/openid-connect/certs"
      route:
        - destination:
            host: "cray-keycloak-http"
            port:
              number: 80
      headers:
        response:
          set:
            Cache-Control: "max-age=300"
    - match:
        - uri:
            prefix: "/keycloak"
      rewrite:
        uri: "/keycloak"
      route:
        - destination:
            host: "cray-keycloak-http"
            port:
              number: 80
